spring.application.name=EasySCB

easy.work.scb.sql.sql-file=123
easy.work.scb.sql.namesql-dept-file=/Users/shaun/IdeaProjects/SCB_Onsit/lt-parent/lt-bcs/src/main/resources/namedsql/proj/DpProjFeedSql.nsql.xml
easy.work.scb.sql.namesql-report-file=/Users/shaun/IdeaProjects/SCB_Onsit/rt-parent/rt-bcs/src/main/resources/namedsql/proj/DpProjFeedSql.nsql.xml