spring.application.name=EasySCB

easy.work.scb.sql.sql-file=/Users/shaun/IdeaProjects/EasyWork/sql
easy.work.scb.sql.namesql-dept-file=/Users/shaun/IdeaProjects/SCB_Onsit/lt-parent/lt-bcs/src/main/resources/namedsql/proj/DpProjFeedSql.nsql.xml
easy.work.scb.sql.namesql-report-file=/Users/shaun/IdeaProjects/SCB_Onsit/rt-parent/rt-bcs/src/main/resources/namedsql/proj/DpProjFeedSql.nsql.xml

easy.work.scb.sql.datasource.url=jdbc:mysql://localhost:3306/temp?useSSL=false&allowPublicKeyRetrieval=true
easy.work.scb.sql.datasource.username=root
easy.work.scb.sql.datasource.password=
easy.work.scb.sql.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

