spring.application.name=EasySCB

easy.work.scb.sql.sql-file=/Users/shaun/IdeaProjects/EasyWork/sql
easy.work.scb.sql.namesql-dept-file=/Users/shaun/IdeaProjects/SCB_Onsit/lt-parent/lt-bcs/src/main/resources/namedsql/proj/DpProjFeedSql.nsql.xml
easy.work.scb.sql.namesql-report-file=/Users/shaun/IdeaProjects/SCB_Onsit/rt-parent/rt-bcs/src/main/resources/namedsql/proj/DpProjFeedSql.nsql.xml

easy.work.scb.feedfile.class.dept-root-path=/Users/shaun/IdeaProjects/SCB_Onsit/lt-batch/src/main/java
easy.work.scb.feedfile.class.report-root-path=/Users/shaun/IdeaProjects/SCB_Onsit/rt-batch/src/main/java













